//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UILayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please check entered data. Inner exception: .
        /// </summary>
        internal static string MsgAddFail {
            get {
                return ResourceManager.GetString("MsgAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was successfully added.
        /// </summary>
        internal static string MsgAddOrderSuccess {
            get {
                return ResourceManager.GetString("MsgAddOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker was successfully added.
        /// </summary>
        internal static string MsgAddWorkerSuccess {
            get {
                return ResourceManager.GetString("MsgAddWorkerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker successfully deleted.
        /// </summary>
        internal static string MsgDeletedWorker {
            get {
                return ResourceManager.GetString("MsgDeletedWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string MsgFail {
            get {
                return ResourceManager.GetString("MsgFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really want to delete this worker?.
        /// </summary>
        internal static string MsgIsDeleteWorker {
            get {
                return ResourceManager.GetString("MsgIsDeleteWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string MsgIsDeleteWorkerCaption {
            get {
                return ResourceManager.GetString("MsgIsDeleteWorkerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker was successfuly updated.
        /// </summary>
        internal static string MsgUpdateWorker {
            get {
                return ResourceManager.GetString("MsgUpdateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker name cannot be white space.
        /// </summary>
        internal static string MsgWorkerEmpty {
            get {
                return ResourceManager.GetString("MsgWorkerEmpty", resourceCulture);
            }
        }
    }
}
